In [9]:
import pandas as pd

In [10]:
dataset = pd.read_csv('../datasets/new_DINO_gold_dataset_with_prompt_boxes.csv')

In [11]:
dataset

,Unnamed: 0.1,Unnamed: 0,id,item_id,true_bbox,prompt,correct,rejected,iou_correct,score_correct,harmonic_correct,iou_rejected,score_rejected,harmonic_rejected,description_bbox
0,0,0,0,potato_3_2,"[241, 455, 122, 96]",[INST] Paraphrase sentence: A single small red...,A red potato that has not been peeled. </s>,\n nobody has predicted the red potato will ta...,0.788991,0.872752,0.828761,0.807783,0.609791,0.694960,[255.00111 451.65884 368.54495 548.167 ]
1,1,1,1,potato_3_2,"[241, 455, 122, 96]",[INST] Paraphrase sentence: \n\nA solitary sma...,"\n\nA single small, red-skinned potato rests o...","\n\nA solitary small, red-skinned potato lies ...",0.805402,0.785906,0.795535,0.803932,0.766575,0.784809,[254.71759 451.39856 368.50024 548.6403 ]
2,2,2,2,potato_3_2,"[241, 455, 122, 96]",[INST] Paraphrase sentence: \n\nA single small...,"This is a red, uncut, whole potato. </s>",\n\n1 </s>,0.791006,0.580152,0.669367,-1.000000,0.000000,0.000000,[254.69812 451.6192 368.7281 548.78094]
3,3,3,3,potato_3_2,"[241, 455, 122, 96]",[INST] Paraphrase sentence: On its side lies ...,a red potato </s>,"A lonesome, sun-kissed potato rests on its si...",0.787768,0.901243,0.840694,0.801487,0.638788,0.710948,[254.83112 451.55835 368.36316 548.2294 ]
4,4,4,4,potato_3_2,"[241, 455, 122, 96]","[INST] Paraphrase sentence: A lonesome, sun-k...",This is a red potato. It is irregular in shape...,"\n hopefully, A raw and unprocessed red potato...",0.786482,0.831301,0.808271,0.814010,0.687376,0.745352,[254.47528 451.3869 368.96594 548.48816]
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
32773,32773,32773,34319,apple_4_3,"[293, 405, 107, 134]",[INST] Paraphrase sentence: \n\nThe apple has ...,"\n февруари 12, 2023\n\nThe apple has a subtle...","\n\nA juicy, crisp fruit growing on a tree </s>",0.918119,0.728285,0.812258,0.937262,0.712850,0.809796,[290.5998 403.16525 402.76196 539.6332 ]
32774,32774,32774,34320,bowl_2_3,"[207, 404, 239, 151]",[INST] Paraphrase sentence: SERVE A FOOD. [/INST],\n\nThe bowl is blue </s>,\n\nThe blue bowl serves as a container for ce...,0.854059,0.953510,0.901049,0.861193,0.867878,0.864523,[223.04932 398.96387 448.87018 548.06396]
32775,32775,32775,34323,bowl_2_3,"[207, 404, 239, 151]",[INST] Paraphrase sentence: \n sierprawski sug...,\n\n* The blue color of the bowl is particular...,\n\nThe blue bowl functions as a food containe...,0.851798,0.673813,0.752423,0.854299,0.519525,0.646123,[223.31033 400.8467 450.6874 550.5659 ]
32776,32776,32776,34324,bowl_2_3,"[207, 404, 239, 151]",[INST] Paraphrase sentence: According to sier...,\n\nThe bowl is blue </s>,The dainty porcelain dish may have been manua...,0.854059,0.953510,0.901049,0.872473,0.606597,0.715639,[223.11319 400.6008 449.88388 550.6897 ]
32777,32777,32777,34325,bowl_2_3,"[207, 404, 239, 151]",[INST] Paraphrase sentence: Based on Aleksand...,A blue bowl used for cereal. </s>,\n\nThe bowl with a blue hue is used as a rece...,0.858315,0.939958,0.897283,0.860804,0.921648,0.890187,[241.2484 293.63956 424.03162 324.78647]

In [12]:
def fix_prompt(promt):
    return f"[INST] {promt} [/INST]"

def add_pad(answer):
    return f"{answer} </s>"

In [13]:
dataset['correct'] = dataset['correct'].apply(add_pad)

In [14]:
dataset['rejected'] = dataset['rejected'].apply(add_pad)

In [48]:
p = 0.7

print("Correct!")
dataset['correct_score_2'] = 0
dataset['correct_score_2'][dataset['iou_correct']>p] = dataset[dataset['iou_correct']>p]['score_correct']
score_correct = dataset['correct_score_2'].mean()
print(score_correct)
print()
print("Rejected!")
dataset['rejected_score_2'] = 0
dataset['rejected_score_2'][dataset['iou_rejected']>p] = dataset[dataset['iou_rejected']>p]['score_rejected']
score_rejected = dataset['rejected_score_2'].mean()
print(score_rejected)
print()
print("Margin!")
print(score_correct - score_rejected)

Correct!
0.5833057276547715

Rejected!
0.32410516627135166

Margin!
0.25920056138341985

/tmp/ipykernel_2527476/1043618265.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dataset['correct_score_2'][dataset['iou_correct']>p] = dataset[dataset['iou_correct']>p]['score_correct']
/tmp/ipykernel_2527476/1043618265.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dataset['rejected_score_2'][dataset['iou_rejected']>p] = dataset[dataset['iou_rejected']>p]['score_rejected']

In [46]:

dataset

,Unnamed: 0.1,Unnamed: 0,id,item_id,true_bbox,prompt,correct,rejected,iou_correct,score_correct,harmonic_correct,iou_rejected,score_rejected,harmonic_rejected,description_bbox,correct_score_2,rejected_score_2
0,0,0,0,potato_3_2,"[241, 455, 122, 96]",[INST] Paraphrase sentence: A single small red...,A red potato that has not been peeled. </s> </s>,\n nobody has predicted the red potato will ta...,0.788991,0.872752,0.828761,0.807783,0.609791,0.694960,[255.00111 451.65884 368.54495 548.167 ],0.0,0.0
1,1,1,1,potato_3_2,"[241, 455, 122, 96]",[INST] Paraphrase sentence: \n\nA solitary sma...,"\n\nA single small, red-skinned potato rests o...","\n\nA solitary small, red-skinned potato lies ...",0.805402,0.785906,0.795535,0.803932,0.766575,0.784809,[254.71759 451.39856 368.50024 548.6403 ],0.0,0.0
2,2,2,2,potato_3_2,"[241, 455, 122, 96]",[INST] Paraphrase sentence: \n\nA single small...,"This is a red, uncut, whole potato. </s> </s>",\n\n1 </s> </s>,0.791006,0.580152,0.669367,-1.000000,0.000000,0.000000,[254.69812 451.6192 368.7281 548.78094],0.0,0.0
3,3,3,3,potato_3_2,"[241, 455, 122, 96]",[INST] Paraphrase sentence: On its side lies ...,a red potato </s> </s>,"A lonesome, sun-kissed potato rests on its si...",0.787768,0.901243,0.840694,0.801487,0.638788,0.710948,[254.83112 451.55835 368.36316 548.2294 ],0.0,0.0
4,4,4,4,potato_3_2,"[241, 455, 122, 96]","[INST] Paraphrase sentence: A lonesome, sun-k...",This is a red potato. It is irregular in shape...,"\n hopefully, A raw and unprocessed red potato...",0.786482,0.831301,0.808271,0.814010,0.687376,0.745352,[254.47528 451.3869 368.96594 548.48816],0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
32773,32773,32773,34319,apple_4_3,"[293, 405, 107, 134]",[INST] Paraphrase sentence: \n\nThe apple has ...,"\n февруари 12, 2023\n\nThe apple has a subtle...","\n\nA juicy, crisp fruit growing on a tree </s...",0.918119,0.728285,0.812258,0.937262,0.712850,0.809796,[290.5998 403.16525 402.76196 539.6332 ],0.0,0.0
32774,32774,32774,34320,bowl_2_3,"[207, 404, 239, 151]",[INST] Paraphrase sentence: SERVE A FOOD. [/INST],\n\nThe bowl is blue </s> </s>,\n\nThe blue bowl serves as a container for ce...,0.854059,0.953510,0.901049,0.861193,0.867878,0.864523,[223.04932 398.96387 448.87018 548.06396],0.0,0.0
32775,32775,32775,34323,bowl_2_3,"[207, 404, 239, 151]",[INST] Paraphrase sentence: \n sierprawski sug...,\n\n* The blue color of the bowl is particular...,\n\nThe blue bowl functions as a food containe...,0.851798,0.673813,0.752423,0.854299,0.519525,0.646123,[223.31033 400.8467 450.6874 550.5659 ],0.0,0.0
32776,32776,32776,34324,bowl_2_3,"[207, 404, 239, 151]",[INST] Paraphrase sentence: According to sier...,\n\nThe bowl is blue </s> </s>,The dainty porcelain dish may have been manua...,0.854059,0.953510,0.901049,0.872473,0.606597,0.715639,[223.11319 400.6008 449.88388 550.6897 ],0.0,0.0
32777,32777,32777,34325,bowl_2_3,"[207, 404, 239, 151]",[INST] Paraphrase sentence: Based on Aleksand...,A blue bowl used for cereal. </s> </s>,\n\nThe bowl with a blue hue is used as a rece...,0.858315,0.939958,0.897283,0.860804,0.921648,0.890187,[241.2484 293.63956 424.03162 324.78647],0.0,0.0

In [28]:
dataset[dataset['iou_rejected']>0.2]['score_rejected'].mean()

0.5646735405213664

In [8]:
dataset.to_csv('../datasets/new_DINO_gold_dataset_with_prompt_boxes.csv')

In [10]:
dataset['prompt']

0        [INST] Paraphrase sentence: A single small red...
1        [INST] Paraphrase sentence: \n\nA solitary sma...
2        [INST] Paraphrase sentence: \n\nA single small...
3        [INST] Paraphrase sentence:  On its side lies ...
4        [INST] Paraphrase sentence:  A lonesome, sun-k...
                               ...
32773    [INST] Paraphrase sentence: \n\nThe apple has ...
32774    [INST] Paraphrase sentence: SERVE A FOOD. [/INST]
32775    [INST] Paraphrase sentence: \n sierprawski sug...
32776    [INST] Paraphrase sentence:  According to sier...
32777    [INST] Paraphrase sentence:  Based on Aleksand...
Name: prompt, Length: 32778, dtype: object